# Job for building
jobs:
  include:
    - if: tag IS present
      os: linux
      language: python
      python: "3.6"
      dist: trusty
    - if: tag IS present
      os: osx
      language: generic
      env: PYTHON=3.6.5

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

# Install dependencies
install:
  - pip install -U -r requirements.txt

# Perform build
script:
  - python setup.py build


# Zip files before deploy
before_deploy:
  - mkdir dist
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      zip -r ../dist/darwin.zip . -x "*.DS_Store";
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      zip -r ../dist/linux.zip .;
    fi
  - cd ../

# Push to github releases
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    

after_deploy:
  - echo "Finished uploading artifacts"
