image: Visual Studio 2015

skip_non_tags: true

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%/Scripts/pip.exe install -U -r requirements.txt"

build_script:
  - "pyinstaller rainbow.py"

artifacts:
  - path: dist/rainbow
