image: Visual Studio 2015

appveyor_repo_tag: true

environment:
  PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%/Scripts/pip.exe install -U -r requirements.txt"

build_script:
  - "%PYTHON%/python.exe setup.py build"

artifacts:
  - path: build
